(set-register ?i '(file . "~/.emacs.d/init.el"))
(set-register ?f '(file . "~/Documents/org/fauxton.org"))
(set-register ?c '(file . "~/Documents/org/cloudant.org"))
(set-register ?h '(file . "~/Documents/org/home.org"))
(set-register ?e '(file . "~/Documents/org/emacs.org"))
(set-register ?m '(file . "~/Documents/org/me.org"))
(set-register ?r '(file . "~/Documents/org/research.org"))
(set-register ?u '(file . "~/src/cloudant/wilson/wilson/user.py"))
(set-register ?s '(file . "~/src/cloudant/cheatsheet.md"))

