- file: path=/home/{{ ansible_ssh_user }}/.vim state=directory
- file: path=/home/{{ ansible_ssh_user }}/.vim/bundle state=directory
- file: path=/home/{{ ansible_ssh_user }}/.vim/autoload state=directory
- file: path=/home/{{ ansible_ssh_user }}/.vim/undodir state=directory

- name: Install vimrc
  copy: src=files/vimrc dest=/home/{{ ansible_ssh_user }}/.vimrc

- name: Install Pathogen
  copy: src=files/pathogen.vim dest=/home/{{ ansible_ssh_user }}/.vim/autoload/pathogen.vim

- name: Install plugins
  git: repo={{ item.repo }}
       dest=/home/{{ ansible_ssh_user }}/.vim/bundle/{{ item.name }}
       update=no
       clone=yes
       accept_hostkey=yes
  with_items:
    - { name: 'ctrlp.vim', repo: 'https://github.com/kien/ctrlp.vim.git' }
    - { name: 'erlang-motions.vim', repo: 'https://github.com/edkolev/erlang-motions.vim.git' }
    - { name: 'tmuxline.vim', repo: 'https://github.com/edkolev/tmuxline.vim.git' }
    - { name: 'vim-airline', repo: 'https://github.com/bling/vim-airline.git' }
    - { name: 'vimerl', repo: 'https://github.com/jimenezrick/vimerl.git' }
    - { name: 'vim-erlang-compiler', repo: 'https://github.com/vim-erlang/vim-erlang-compiler.git' }
    - { name: 'vim-erlang-omnicomplete', repo: 'https://github.com/vim-erlang/vim-erlang-omnicomplete.git' }
    - { name: 'vim-erlang-tags', repo: 'https://github.com/vim-erlang/vim-erlang-tags.git' }
    - { name: 'vim-fugitive', repo: 'https://github.com/tpope/vim-fugitive.git' }
    - { name: 'vim-sensible', repo: 'https://github.com/tpope/vim-sensible.git' }
    - { name: 'vim-commentary', repo: 'https://github.com/tpope/vim-commentary.git' }
    - { name: 'vim-vividchalk', repo: 'https://github.com/tpope/vim-vividchalk.git' }

# TODO: install user_default for autoloading
